(define (domain viatge)
	(:requirements :strips :typing :adl :equality :fluents)
	(:types ciudad hotel vuelo)
	(:functions
		(actual)
		(ciudades-totales)
	)
	(:predicates
		(es-de ?c - ciudad ?h - hotel)
		(va-a ?v - vuelo ?c1 - ciudad ?c2 - ciudad)
		(ciudad-empty ?c - ciudad)
		(esta-a ?c - ciudad)
		(inicial)
	)

	(:action ciudad-inicio
	  :parameters (?c - ciudad ?h - hotel)
	  :precondition (and (inicial) (es-de ?c ?h))
	  :effect (and 	(esta-a ?c)
				   	(not (ciudad-empty ?c))
				   	(increase (actual) 1)
				   	(not (inicial))
		       )
	)

	(:action reservar-vol-hotel
	  	:parameters (?v - vuelo ?c1 - ciudad ?c2 - ciudad ?h - hotel)
		:precondition (and (not (inicial)) 
						   (esta-a ?c1) 
						   (not (ciudad-empty ?c1)) 
						   (ciudad-empty ?c2) 
						   (va-a ?v ?c1 ?c2)
						   (es-de ?c2 ?h)
					  )
		:effect (and (not (esta-a ?c1)) 
					 (esta-a ?c2) 
					 (not (ciudad-empty ?c2))
					 (increase (actual) 1)
				)
	)
	
)