(define (problem problema3)
  (:domain viatge)

  (:objects
    ciutat-1 ciutat-2 ciutat-3 ciutat-4 ciutat-5 ciutat-6 ciutat-7 ciutat-8 ciutat-9 ciutat-10  - ciudad
    hotel-1 hotel-2 hotel-3 hotel-4 hotel-5 hotel-6 hotel-7 hotel-8 hotel-9 hotel-10 hotel-11 hotel-12 hotel-13 hotel-14 hotel-15 hotel-16 hotel-17 hotel-18 hotel-19 hotel-20 hotel-21 hotel-22 hotel-23 hotel-24 hotel-25  - hotel
    vol-1 vol-2 vol-3 vol-4 vol-5 vol-6 vol-7 vol-8 vol-9 vol-10 vol-11 vol-12 vol-13 vol-14 vol-15 vol-16  - vuelo
  )

  (:init
    (inicial)
    (= (actual) 0)
    (= (min-dias-totales) 6)
    (= (ciudades-totales) 3)
    (= (dias-totales) 0)
    (= (interes-total) 0)
    (= (precio-total) 0)
    (ciudad-empty ciutat-1)
    (= (dias-ciudad ciutat-1) 0)
    (= (min-dias-ciudad ciutat-1) 1)
    (= (max-dias-ciudad ciutat-1) 2)
    (ciudad-empty ciutat-2)
    (= (dias-ciudad ciutat-2) 0)
    (= (min-dias-ciudad ciutat-2) 1)
    (= (max-dias-ciudad ciutat-2) 2)
    (ciudad-empty ciutat-3)
    (= (dias-ciudad ciutat-3) 0)
    (= (min-dias-ciudad ciutat-3) 1)
    (= (max-dias-ciudad ciutat-3) 4)
    (ciudad-empty ciutat-4)
    (= (dias-ciudad ciutat-4) 0)
    (= (min-dias-ciudad ciutat-4) 2)
    (= (max-dias-ciudad ciutat-4) 4)
    (ciudad-empty ciutat-5)
    (= (dias-ciudad ciutat-5) 0)
    (= (min-dias-ciudad ciutat-5) 2)
    (= (max-dias-ciudad ciutat-5) 2)
    (ciudad-empty ciutat-6)
    (= (dias-ciudad ciutat-6) 0)
    (= (min-dias-ciudad ciutat-6) 2)
    (= (max-dias-ciudad ciutat-6) 1)
    (ciudad-empty ciutat-7)
    (= (dias-ciudad ciutat-7) 0)
    (= (min-dias-ciudad ciutat-7) 2)
    (= (max-dias-ciudad ciutat-7) 3)
    (ciudad-empty ciutat-8)
    (= (dias-ciudad ciutat-8) 0)
    (= (min-dias-ciudad ciutat-8) 1)
    (= (max-dias-ciudad ciutat-8) 2)
    (ciudad-empty ciutat-9)
    (= (dias-ciudad ciutat-9) 0)
    (= (min-dias-ciudad ciutat-9) 2)
    (= (max-dias-ciudad ciutat-9) 3)
    (ciudad-empty ciutat-10)
    (= (dias-ciudad ciutat-10) 0)
    (= (min-dias-ciudad ciutat-10) 2)
    (= (max-dias-ciudad ciutat-10) 2)
    (= (interes ciutat-1) 2)
    (= (interes ciutat-2) 3)
    (= (interes ciutat-3) 5)
    (= (interes ciutat-4) 2)
    (= (interes ciutat-5) 3)
    (= (interes ciutat-6) 5)
    (= (interes ciutat-7) 4)
    (= (interes ciutat-8) 4)
    (= (interes ciutat-9) 4)
    (= (interes ciutat-10) 4)
    (es-de ciutat-1 hotel-1)
    (es-de ciutat-1 hotel-2)
    (es-de ciutat-1 hotel-3)
    (es-de ciutat-2 hotel-4)
    (es-de ciutat-2 hotel-5)
    (es-de ciutat-3 hotel-6)
    (es-de ciutat-3 hotel-7)
    (es-de ciutat-4 hotel-8)
    (es-de ciutat-4 hotel-9)
    (es-de ciutat-4 hotel-10)
    (es-de ciutat-5 hotel-11)
    (es-de ciutat-5 hotel-12)
    (es-de ciutat-5 hotel-13)
    (es-de ciutat-6 hotel-14)
    (es-de ciutat-6 hotel-15)
    (es-de ciutat-6 hotel-16)
    (es-de ciutat-7 hotel-17)
    (es-de ciutat-7 hotel-18)
    (es-de ciutat-8 hotel-19)
    (es-de ciutat-9 hotel-20)
    (es-de ciutat-9 hotel-21)
    (es-de ciutat-10 hotel-22)
    (es-de ciutat-10 hotel-23)
    (es-de ciutat-10 hotel-24)
    (= (precio-hotel hotel-1) 161)
    (= (precio-hotel hotel-2) 60)
    (= (precio-hotel hotel-3) 216)
    (= (precio-hotel hotel-4) 225)
    (= (precio-hotel hotel-5) 176)
    (= (precio-hotel hotel-6) 237)
    (= (precio-hotel hotel-7) 202)
    (= (precio-hotel hotel-8) 138)
    (= (precio-hotel hotel-9) 50)
    (= (precio-hotel hotel-10) 72)
    (= (precio-hotel hotel-11) 184)
    (= (precio-hotel hotel-12) 117)
    (= (precio-hotel hotel-13) 65)
    (= (precio-hotel hotel-14) 213)
    (= (precio-hotel hotel-15) 94)
    (= (precio-hotel hotel-16) 166)
    (= (precio-hotel hotel-17) 114)
    (= (precio-hotel hotel-18) 155)
    (= (precio-hotel hotel-19) 61)
    (= (precio-hotel hotel-20) 57)
    (= (precio-hotel hotel-21) 126)
    (= (precio-hotel hotel-22) 222)
    (= (precio-hotel hotel-23) 244)
    (= (precio-hotel hotel-24) 136)
    (= (precio-hotel hotel-25) 230)
    (va-a vol-1 ciutat-1 ciutat-3)
    (= (precio-vuelo vol-1) 119)
    (va-a vol-2 ciutat-2 ciutat-10)
    (= (precio-vuelo vol-2) 138)
    (va-a vol-3 ciutat-3 ciutat-9)
    (= (precio-vuelo vol-3) 134)
    (va-a vol-4 ciutat-4 ciutat-8)
    (= (precio-vuelo vol-4) 100)
    (va-a vol-5 ciutat-4 ciutat-9)
    (= (precio-vuelo vol-5) 53)
    (va-a vol-6 ciutat-5 ciutat-7)
    (= (precio-vuelo vol-6) 84)
    (va-a vol-7 ciutat-5 ciutat-9)
    (= (precio-vuelo vol-7) 83)
    (va-a vol-8 ciutat-5 ciutat-10)
    (= (precio-vuelo vol-8) 128)
    (va-a vol-9 ciutat-7 ciutat-3)
    (= (precio-vuelo vol-9) 64)
    (va-a vol-10 ciutat-7 ciutat-4)
    (= (precio-vuelo vol-10) 86)
    (va-a vol-11 ciutat-7 ciutat-5)
    (= (precio-vuelo vol-11) 67)
    (va-a vol-12 ciutat-7 ciutat-9)
    (= (precio-vuelo vol-12) 88)
    (va-a vol-13 ciutat-7 ciutat-10)
    (= (precio-vuelo vol-13) 121)
    (va-a vol-14 ciutat-8 ciutat-10)
    (= (precio-vuelo vol-14) 129)
    (va-a vol-15 ciutat-9 ciutat-3)
    (= (precio-vuelo vol-15) 101)
  )
  (:metric minimize (+ (* (interes-total) 2) (* (precio-total) 0)))

  (:goal
  	(and (= (actual) (ciudades-totales)) (>= (dias-totales) (min-dias-totales)))
  )
)
