(define (problem problema5)
  (:domain viatge)

  (:objects
    ciutat-1 ciutat-2 ciutat-3 ciutat-4 ciutat-5  - ciudad
    hotel-1 hotel-2 hotel-3 hotel-4 hotel-5 hotel-6 hotel-7 hotel-8 hotel-9 hotel-10 hotel-11  - hotel
    vol-1 vol-2 vol-3 vol-4 vol-5 vol-6 vol-7 vol-8 vol-9 vol-10 vol-11 vol-12 vol-13 vol-14 vol-15 vol-16 vol-17  - vuelo
  )

  (:init
    (inicial)
    (= (actual) 0)
    (= (min-dias-totales) 3)
    (= (ciudades-totales) 2)
    (= (dias-totales) 0)
    (= (precio-total) 0)
    (ciudad-empty ciutat-1)
    (= (dias-ciudad ciutat-1) 0)
    (ciudad-empty ciutat-2)
    (= (dias-ciudad ciutat-2) 0)
    (ciudad-empty ciutat-3)
    (= (dias-ciudad ciutat-3) 0)
    (ciudad-empty ciutat-4)
    (= (dias-ciudad ciutat-4) 0)
    (ciudad-empty ciutat-5)
    (= (dias-ciudad ciutat-5) 0)
    (= (min-dias-ciudad) 1)
    (= (max-dias-ciudad) 4)
    (es-de ciutat-1 hotel-1)
    (es-de ciutat-1 hotel-2)
    (es-de ciutat-1 hotel-3)
    (es-de ciutat-2 hotel-4)
    (es-de ciutat-2 hotel-5)
    (es-de ciutat-2 hotel-6)
    (es-de ciutat-2 hotel-7)
    (es-de ciutat-3 hotel-8)
    (es-de ciutat-4 hotel-9)
    (es-de ciutat-5 hotel-10)
    (= (precio-hotel hotel-1) 97)
    (= (precio-hotel hotel-2) 229)
    (= (precio-hotel hotel-3) 221)
    (= (precio-hotel hotel-4) 111)
    (= (precio-hotel hotel-5) 234)
    (= (precio-hotel hotel-6) 210)
    (= (precio-hotel hotel-7) 190)
    (= (precio-hotel hotel-8) 52)
    (= (precio-hotel hotel-9) 101)
    (= (precio-hotel hotel-10) 90)
    (= (precio-hotel hotel-11) 231)
    (va-a vol-1 ciutat-1 ciutat-2)
    (va-a vol-2 ciutat-1 ciutat-3)
    (va-a vol-3 ciutat-1 ciutat-4)
    (va-a vol-4 ciutat-2 ciutat-1)
    (va-a vol-5 ciutat-2 ciutat-3)
    (va-a vol-6 ciutat-2 ciutat-4)
    (va-a vol-7 ciutat-3 ciutat-1)
    (va-a vol-8 ciutat-3 ciutat-2)
    (va-a vol-9 ciutat-3 ciutat-4)
    (va-a vol-10 ciutat-3 ciutat-5)
    (va-a vol-11 ciutat-4 ciutat-1)
    (va-a vol-12 ciutat-4 ciutat-5)
    (va-a vol-13 ciutat-5 ciutat-1)
    (va-a vol-14 ciutat-5 ciutat-2)
    (va-a vol-15 ciutat-5 ciutat-3)
    (va-a vol-16 ciutat-5 ciutat-4)
    (= (precio-vuelo vol-1) 61)
    (= (precio-vuelo vol-2) 35)
    (= (precio-vuelo vol-3) 92)
    (= (precio-vuelo vol-4) 124)
    (= (precio-vuelo vol-5) 50)
    (= (precio-vuelo vol-6) 42)
    (= (precio-vuelo vol-7) 58)
    (= (precio-vuelo vol-8) 87)
    (= (precio-vuelo vol-9) 60)
    (= (precio-vuelo vol-10) 59)
    (= (precio-vuelo vol-11) 115)
    (= (precio-vuelo vol-12) 119)
    (= (precio-vuelo vol-13) 34)
    (= (precio-vuelo vol-14) 43)
    (= (precio-vuelo vol-15) 128)
    (= (precio-vuelo vol-16) 126)
    (= (precio-vuelo vol-17) 107)
  )
  (:metric minimize (precio-total))

  (:goal
  	(and (= (actual) (ciudades-totales)) (>= (dias-totales) (min-dias-totales)) (>= (precio-total) (min-precio)) (<= (precio-total) (max-precio))
  ))
)
