(define (problem instancia5)
  (:domain viatge)

  (:objects
    ciutat-1 ciutat-2 ciutat-3 ciutat-4 ciutat-5  - ciudad
    hotel-1 hotel-2 hotel-3 hotel-4 hotel-5 hotel-6  - hotel
    vol-1 vol-2 vol-3 vol-4 vol-5 vol-6 vol-7 vol-8 vol-9 vol-10 vol-11 vol-12 vol-13 vol-14 vol-15 vol-16 vol-17  - vuelo
  )

  (:init
    (inicial)
    (= (min-precio) 79)
    (= (max-precio) 1282)
    (= (actual) 0)
    (= (min-dias-totales) 2)
    (= (ciudades-totales) 2)
    (= (dias-totales) 0)
    (= (precio-total) 0)
    (ciudad-empty ciutat-1)
    (= (dias-ciudad ciutat-1) 0)
    (ciudad-empty ciutat-2)
    (= (dias-ciudad ciutat-2) 0)
    (ciudad-empty ciutat-3)
    (= (dias-ciudad ciutat-3) 0)
    (ciudad-empty ciutat-4)
    (= (dias-ciudad ciutat-4) 0)
    (ciudad-empty ciutat-5)
    (= (dias-ciudad ciutat-5) 0)
    (= (min-dias-ciudad) 2)
    (= (max-dias-ciudad) 3)
    (es-de ciutat-1 hotel-1)
    (es-de ciutat-2 hotel-2)
    (es-de ciutat-3 hotel-3)
    (es-de ciutat-4 hotel-4)
    (es-de ciutat-5 hotel-5)
    (= (precio-hotel hotel-1) 95)
    (= (precio-hotel hotel-2) 96)
    (= (precio-hotel hotel-3) 48)
    (= (precio-hotel hotel-4) 159)
    (= (precio-hotel hotel-5) 47)
    (= (precio-hotel hotel-6) 191)
    (va-a vol-1 ciutat-1 ciutat-2)
    (va-a vol-2 ciutat-1 ciutat-3)
    (va-a vol-3 ciutat-2 ciutat-1)
    (va-a vol-4 ciutat-2 ciutat-3)
    (va-a vol-5 ciutat-2 ciutat-4)
    (va-a vol-6 ciutat-2 ciutat-5)
    (va-a vol-7 ciutat-3 ciutat-1)
    (va-a vol-8 ciutat-3 ciutat-2)
    (va-a vol-9 ciutat-3 ciutat-4)
    (va-a vol-10 ciutat-4 ciutat-1)
    (va-a vol-11 ciutat-4 ciutat-2)
    (va-a vol-12 ciutat-4 ciutat-3)
    (va-a vol-13 ciutat-4 ciutat-5)
    (va-a vol-14 ciutat-5 ciutat-1)
    (va-a vol-15 ciutat-5 ciutat-2)
    (va-a vol-16 ciutat-5 ciutat-4)
    (= (precio-vuelo vol-1) 52)
    (= (precio-vuelo vol-2) 127)
    (= (precio-vuelo vol-3) 57)
    (= (precio-vuelo vol-4) 125)
    (= (precio-vuelo vol-5) 78)
    (= (precio-vuelo vol-6) 80)
    (= (precio-vuelo vol-7) 31)
    (= (precio-vuelo vol-8) 112)
    (= (precio-vuelo vol-9) 113)
    (= (precio-vuelo vol-10) 125)
    (= (precio-vuelo vol-11) 81)
    (= (precio-vuelo vol-12) 65)
    (= (precio-vuelo vol-13) 108)
    (= (precio-vuelo vol-14) 88)
    (= (precio-vuelo vol-15) 129)
    (= (precio-vuelo vol-16) 108)
    (= (precio-vuelo vol-17) 90)
  )
  (:goal
  	(and (= (actual) (ciudades-totales)) (>= (dias-totales) (min-dias-totales)) (>= (precio-total) (min-precio)) (<= (precio-total) (max-precio))
  ))

  (:metric minimize (precio-total))
)
