(define (problem instancia8)
  (:domain viatge)

  (:objects
    ciutat-1 ciutat-2 ciutat-3 ciutat-4 ciutat-5 ciutat-6 ciutat-7 ciutat-8  - ciudad
    hotel-1 hotel-2 hotel-3 hotel-4 hotel-5 hotel-6 hotel-7 hotel-8 hotel-9  - hotel
    vol-1 vol-2 vol-3 vol-4 vol-5 vol-6 vol-7 vol-8 vol-9 vol-10 vol-11 vol-12 vol-13 vol-14 vol-15 vol-16 vol-17 vol-18 vol-19 vol-20 vol-21 vol-22 vol-23 vol-24 vol-25 vol-26 vol-27 vol-28 vol-29 vol-30 vol-31 vol-32 vol-33 vol-34 vol-35  - vuelo
  )

  (:init
    (inicial)
    (= (min-precio) 151)
    (= (max-precio) 2627)
    (= (actual) 0)
    (= (min-dias-totales) 4)
    (= (ciudades-totales) 4)
    (= (dias-totales) 0)
    (= (precio-total) 0)
    (ciudad-empty ciutat-1)
    (= (dias-ciudad ciutat-1) 0)
    (ciudad-empty ciutat-2)
    (= (dias-ciudad ciutat-2) 0)
    (ciudad-empty ciutat-3)
    (= (dias-ciudad ciutat-3) 0)
    (ciudad-empty ciutat-4)
    (= (dias-ciudad ciutat-4) 0)
    (ciudad-empty ciutat-5)
    (= (dias-ciudad ciutat-5) 0)
    (ciudad-empty ciutat-6)
    (= (dias-ciudad ciutat-6) 0)
    (ciudad-empty ciutat-7)
    (= (dias-ciudad ciutat-7) 0)
    (ciudad-empty ciutat-8)
    (= (dias-ciudad ciutat-8) 0)
    (= (min-dias-ciudad) 1)
    (= (max-dias-ciudad) 2)
    (es-de ciutat-1 hotel-1)
    (es-de ciutat-2 hotel-2)
    (es-de ciutat-3 hotel-3)
    (es-de ciutat-4 hotel-4)
    (es-de ciutat-5 hotel-5)
    (es-de ciutat-6 hotel-6)
    (es-de ciutat-7 hotel-7)
    (es-de ciutat-8 hotel-8)
    (= (precio-hotel hotel-1) 154)
    (= (precio-hotel hotel-2) 120)
    (= (precio-hotel hotel-3) 115)
    (= (precio-hotel hotel-4) 116)
    (= (precio-hotel hotel-5) 216)
    (= (precio-hotel hotel-6) 155)
    (= (precio-hotel hotel-7) 96)
    (= (precio-hotel hotel-8) 71)
    (= (precio-hotel hotel-9) 53)
    (va-a vol-1 ciutat-1 ciutat-2)
    (va-a vol-2 ciutat-1 ciutat-3)
    (va-a vol-3 ciutat-1 ciutat-4)
    (va-a vol-4 ciutat-1 ciutat-5)
    (va-a vol-5 ciutat-1 ciutat-6)
    (va-a vol-6 ciutat-1 ciutat-7)
    (va-a vol-7 ciutat-2 ciutat-1)
    (va-a vol-8 ciutat-2 ciutat-3)
    (va-a vol-9 ciutat-2 ciutat-7)
    (va-a vol-10 ciutat-3 ciutat-1)
    (va-a vol-11 ciutat-3 ciutat-2)
    (va-a vol-12 ciutat-3 ciutat-4)
    (va-a vol-13 ciutat-3 ciutat-6)
    (va-a vol-14 ciutat-3 ciutat-7)
    (va-a vol-15 ciutat-4 ciutat-3)
    (va-a vol-16 ciutat-4 ciutat-6)
    (va-a vol-17 ciutat-4 ciutat-7)
    (va-a vol-18 ciutat-4 ciutat-8)
    (va-a vol-19 ciutat-5 ciutat-1)
    (va-a vol-20 ciutat-5 ciutat-2)
    (va-a vol-21 ciutat-5 ciutat-8)
    (va-a vol-22 ciutat-6 ciutat-1)
    (va-a vol-23 ciutat-6 ciutat-2)
    (va-a vol-24 ciutat-6 ciutat-3)
    (va-a vol-25 ciutat-6 ciutat-5)
    (va-a vol-26 ciutat-6 ciutat-8)
    (va-a vol-27 ciutat-7 ciutat-5)
    (va-a vol-28 ciutat-7 ciutat-6)
    (va-a vol-29 ciutat-8 ciutat-2)
    (va-a vol-30 ciutat-8 ciutat-3)
    (va-a vol-31 ciutat-8 ciutat-4)
    (va-a vol-32 ciutat-8 ciutat-5)
    (va-a vol-33 ciutat-8 ciutat-6)
    (va-a vol-34 ciutat-8 ciutat-7)
    (= (precio-vuelo vol-1) 64)
    (= (precio-vuelo vol-2) 79)
    (= (precio-vuelo vol-3) 42)
    (= (precio-vuelo vol-4) 46)
    (= (precio-vuelo vol-5) 115)
    (= (precio-vuelo vol-6) 96)
    (= (precio-vuelo vol-7) 46)
    (= (precio-vuelo vol-8) 81)
    (= (precio-vuelo vol-9) 95)
    (= (precio-vuelo vol-10) 48)
    (= (precio-vuelo vol-11) 105)
    (= (precio-vuelo vol-12) 100)
    (= (precio-vuelo vol-13) 93)
    (= (precio-vuelo vol-14) 80)
    (= (precio-vuelo vol-15) 32)
    (= (precio-vuelo vol-16) 54)
    (= (precio-vuelo vol-17) 101)
    (= (precio-vuelo vol-18) 112)
    (= (precio-vuelo vol-19) 91)
    (= (precio-vuelo vol-20) 36)
    (= (precio-vuelo vol-21) 82)
    (= (precio-vuelo vol-22) 56)
    (= (precio-vuelo vol-23) 31)
    (= (precio-vuelo vol-24) 101)
    (= (precio-vuelo vol-25) 50)
    (= (precio-vuelo vol-26) 78)
    (= (precio-vuelo vol-27) 86)
    (= (precio-vuelo vol-28) 63)
    (= (precio-vuelo vol-29) 114)
    (= (precio-vuelo vol-30) 98)
    (= (precio-vuelo vol-31) 86)
    (= (precio-vuelo vol-32) 67)
    (= (precio-vuelo vol-33) 114)
    (= (precio-vuelo vol-34) 58)
    (= (precio-vuelo vol-35) 111)
  )
  (:goal
  	(and (= (actual) (ciudades-totales)) (>= (dias-totales) (min-dias-totales)) (>= (precio-total) (min-precio)) (<= (precio-total) (max-precio))
  ))

  (:metric minimize (precio-total))
)
