(define (problem instancia6)
  (:domain viatge)

  (:objects
    ciutat-1 ciutat-2 ciutat-3 ciutat-4 ciutat-5 ciutat-6  - ciudad
    hotel-1 hotel-2 hotel-3 hotel-4 hotel-5 hotel-6 hotel-7  - hotel
    vol-1 vol-2 vol-3 vol-4 vol-5 vol-6 vol-7 vol-8 vol-9 vol-10 vol-11 vol-12 vol-13 vol-14 vol-15 vol-16 vol-17 vol-18 vol-19 vol-20 vol-21 vol-22 vol-23 vol-24  - vuelo
  )

  (:init
    (inicial)
    (= (min-precio) 124)
    (= (max-precio) 1898)
    (= (actual) 0)
    (= (min-dias-totales) 3)
    (= (ciudades-totales) 3)
    (= (dias-totales) 0)
    (= (precio-total) 0)
    (ciudad-empty ciutat-1)
    (= (dias-ciudad ciutat-1) 0)
    (ciudad-empty ciutat-2)
    (= (dias-ciudad ciutat-2) 0)
    (ciudad-empty ciutat-3)
    (= (dias-ciudad ciutat-3) 0)
    (ciudad-empty ciutat-4)
    (= (dias-ciudad ciutat-4) 0)
    (ciudad-empty ciutat-5)
    (= (dias-ciudad ciutat-5) 0)
    (ciudad-empty ciutat-6)
    (= (dias-ciudad ciutat-6) 0)
    (= (min-dias-ciudad) 1)
    (= (max-dias-ciudad) 4)
    (es-de ciutat-1 hotel-1)
    (es-de ciutat-2 hotel-2)
    (es-de ciutat-3 hotel-3)
    (es-de ciutat-4 hotel-4)
    (es-de ciutat-5 hotel-5)
    (es-de ciutat-6 hotel-6)
    (= (precio-hotel hotel-1) 159)
    (= (precio-hotel hotel-2) 48)
    (= (precio-hotel hotel-3) 200)
    (= (precio-hotel hotel-4) 167)
    (= (precio-hotel hotel-5) 110)
    (= (precio-hotel hotel-6) 167)
    (= (precio-hotel hotel-7) 46)
    (va-a vol-1 ciutat-1 ciutat-2)
    (va-a vol-2 ciutat-1 ciutat-4)
    (va-a vol-3 ciutat-1 ciutat-5)
    (va-a vol-4 ciutat-1 ciutat-6)
    (va-a vol-5 ciutat-2 ciutat-1)
    (va-a vol-6 ciutat-2 ciutat-4)
    (va-a vol-7 ciutat-2 ciutat-5)
    (va-a vol-8 ciutat-2 ciutat-6)
    (va-a vol-9 ciutat-3 ciutat-1)
    (va-a vol-10 ciutat-3 ciutat-4)
    (va-a vol-11 ciutat-3 ciutat-5)
    (va-a vol-12 ciutat-3 ciutat-6)
    (va-a vol-13 ciutat-4 ciutat-2)
    (va-a vol-14 ciutat-4 ciutat-3)
    (va-a vol-15 ciutat-4 ciutat-5)
    (va-a vol-16 ciutat-4 ciutat-6)
    (va-a vol-17 ciutat-5 ciutat-1)
    (va-a vol-18 ciutat-5 ciutat-3)
    (va-a vol-19 ciutat-5 ciutat-6)
    (va-a vol-20 ciutat-6 ciutat-1)
    (va-a vol-21 ciutat-6 ciutat-2)
    (va-a vol-22 ciutat-6 ciutat-3)
    (va-a vol-23 ciutat-6 ciutat-4)
    (= (precio-vuelo vol-1) 110)
    (= (precio-vuelo vol-2) 76)
    (= (precio-vuelo vol-3) 77)
    (= (precio-vuelo vol-4) 122)
    (= (precio-vuelo vol-5) 101)
    (= (precio-vuelo vol-6) 93)
    (= (precio-vuelo vol-7) 86)
    (= (precio-vuelo vol-8) 42)
    (= (precio-vuelo vol-9) 114)
    (= (precio-vuelo vol-10) 80)
    (= (precio-vuelo vol-11) 65)
    (= (precio-vuelo vol-12) 128)
    (= (precio-vuelo vol-13) 122)
    (= (precio-vuelo vol-14) 92)
    (= (precio-vuelo vol-15) 96)
    (= (precio-vuelo vol-16) 53)
    (= (precio-vuelo vol-17) 31)
    (= (precio-vuelo vol-18) 86)
    (= (precio-vuelo vol-19) 55)
    (= (precio-vuelo vol-20) 78)
    (= (precio-vuelo vol-21) 37)
    (= (precio-vuelo vol-22) 95)
    (= (precio-vuelo vol-23) 122)
    (= (precio-vuelo vol-24) 102)
  )
  (:goal
  	(and (= (actual) (ciudades-totales)) (>= (dias-totales) (min-dias-totales)) (>= (precio-total) (min-precio)) (<= (precio-total) (max-precio))
  ))

  (:metric minimize (precio-total))
)
