(define (problem instancia4)
  (:domain viatge)

  (:objects
    ciutat-1 ciutat-2 ciutat-3 ciutat-4  - ciudad
    hotel-1 hotel-2 hotel-3 hotel-4 hotel-5  - hotel
    vol-1 vol-2 vol-3 vol-4 vol-5 vol-6 vol-7 vol-8 vol-9 vol-10 vol-11 vol-12 vol-13  - vuelo
  )

  (:init
    (inicial)
    (= (min-precio) 119)
    (= (max-precio) 1552)
    (= (actual) 0)
    (= (min-dias-totales) 2)
    (= (ciudades-totales) 2)
    (= (dias-totales) 0)
    (= (precio-total) 0)
    (ciudad-empty ciutat-1)
    (= (dias-ciudad ciutat-1) 0)
    (ciudad-empty ciutat-2)
    (= (dias-ciudad ciutat-2) 0)
    (ciudad-empty ciutat-3)
    (= (dias-ciudad ciutat-3) 0)
    (ciudad-empty ciutat-4)
    (= (dias-ciudad ciutat-4) 0)
    (= (min-dias-ciudad) 2)
    (= (max-dias-ciudad) 5)
    (es-de ciutat-1 hotel-1)
    (es-de ciutat-2 hotel-2)
    (es-de ciutat-3 hotel-3)
    (es-de ciutat-4 hotel-4)
    (= (precio-hotel hotel-1) 226)
    (= (precio-hotel hotel-2) 213)
    (= (precio-hotel hotel-3) 132)
    (= (precio-hotel hotel-4) 85)
    (= (precio-hotel hotel-5) 162)
    (va-a vol-1 ciutat-1 ciutat-2)
    (va-a vol-2 ciutat-1 ciutat-3)
    (va-a vol-3 ciutat-1 ciutat-4)
    (va-a vol-4 ciutat-2 ciutat-1)
    (va-a vol-5 ciutat-2 ciutat-3)
    (va-a vol-6 ciutat-2 ciutat-4)
    (va-a vol-7 ciutat-3 ciutat-1)
    (va-a vol-8 ciutat-3 ciutat-2)
    (va-a vol-9 ciutat-3 ciutat-4)
    (va-a vol-10 ciutat-4 ciutat-1)
    (va-a vol-11 ciutat-4 ciutat-2)
    (va-a vol-12 ciutat-4 ciutat-3)
    (= (precio-vuelo vol-1) 76)
    (= (precio-vuelo vol-2) 85)
    (= (precio-vuelo vol-3) 117)
    (= (precio-vuelo vol-4) 69)
    (= (precio-vuelo vol-5) 79)
    (= (precio-vuelo vol-6) 97)
    (= (precio-vuelo vol-7) 68)
    (= (precio-vuelo vol-8) 104)
    (= (precio-vuelo vol-9) 113)
    (= (precio-vuelo vol-10) 30)
    (= (precio-vuelo vol-11) 86)
    (= (precio-vuelo vol-12) 36)
    (= (precio-vuelo vol-13) 31)
  )
  (:goal
  	(and (= (actual) (ciudades-totales)) (>= (dias-totales) (min-dias-totales)) (>= (precio-total) (min-precio)) (<= (precio-total) (max-precio))
  ))

  (:metric minimize (precio-total))
)
